""" Errors generated by this module
"""


class ConfigException(Exception):
    pass


class FillValueException(Exception):
    """ All of a tile is "fill" values
    """
    pass


class ProductNotFoundException(Exception):
    pass


class ConsistencyError(Exception):
    pass
